### ISSUE TITLE
Requirements for mikrotik_router not found: ['librouteros>=3.4.1']

### ISSUE THREAD

**Issue by Extrapilot1** [tomaae/homeassistant-mikrotik_router#419]
## Describe the issue
After installing update posted today, Mikrotik integration will not load, and yields the error:  Setup failed for custom integration 'mikrotik_router': Requirements for mikrotik_router not found: ['librouteros>=3.4.1']

## How to reproduce the issue
Install update on previously running/stable platform

## Expected behavior
A running integration

## Software versions

 - Home Assistant version: 2025.4.4
 - Mikrotik Router integration version: whatever was released today- its not running, and reads 0.0.0
 - Mikrotik Hardware: RBD52G (HAP AC2)
 - RouterOS version: 7.19beta8

**Comment by tomaae** [comment]
That is not a problem with integration. seems like you have something broken with your python/pip installation.

Cant say I'm surprised tho, I had this issue with base HA installation not automatically downloading its own packages like UI, when upgrading to python 3.13 and HA2025.4.
But that is direct pip install on debian not usual docker/HAOS.

**Comment by Lieta2** [comment]
Same on my setup.

**Comment by Extrapilot1** [comment]
Well, its not a broken python install per se. There is a bug in HA's networking for how it deals with DNS vs the Mikrotik DNS server. If HA is pointing at Mikrotik's, for whatever reason, there is a problem with some address resolution. So far, this is the only installer that has seen it for my install, and I have a lot of integrations. Regardless, for me, a workaround is to alter the HA network settings, and set the DNS to a known good external IP like 1.1.1.1. A reboot may be needed on HA- not sure. Mine was fine without. Then a redownload of the Mikrotik integration via HACS and it is working fine. Paradoxical- seems possible this is the only app I have seen this problem with specifically because it is a Mikrotik-based integration, and I use Mikrotik's DNS server.

**Comment by Lieta2** [comment]
Thank you, Extrapilot1. Changing DNS server from Mikrotik to 1.1.1.1 resolved the issue. Which addresses aren't resolved via Mikrotik DNS?

**Comment by Extrapilot1** [comment]
Happy this helped. I havent had time to look into this via Wireshark etc. What I did find is that there were a lot of server not found errors in the system log, where those were valid URLs from my desktop (which is on the same physical network/subnet). It isnt Adblock etc running locally- you can disable/remove that and the problem remains, even after a reboot of HA's platform. I suspect this is some paradoxical condition where if HA is pointing at Mikrotik for DNS, and Mikrotik is pointing at Adblock etc on HA which is itself configured for some external DNS server, that there is a problem if the Mikrotik- related service(s) are locked/frozen for the update. Not sure why- this is an add-in, not a replacement for HA's core DNS system. 

It seems unlikely to be some generic DNS resolution thing, since I dont see these URL resolution problems with other integrations (i..e OpenWeather, etc).

**Comment by tomaae** [comment]
that it an interesting issue. Cant see how mikrotik dns could affect just one application, but well. I'm pretty sure this didnt happen before HA forced recent python upgrade

**Comment by AlexDevera** [comment]
I’m having the same issue. After updating the integration, everything crashed.

**Comment by tomaae** [comment]
read above for fix

**Comment by qtronixx** [comment]
Indeed, after installing DNS 1.1.1.1 everything started working.

**Comment by Extrapilot1** [comment]
Unfortunately, with every Home Assistant update, the integration will fail again. And that tends to suggest this isnt a broken install- a new HASS OS is supposed to update all dependencies and fix any missing files. So, it seems there is something in play with a particular setup- either some combo of integrations, or Docker vs native  on RPI4/5 etc. It doesnt take a lot of time to swap DNS back and forth, but this shouldnt be necessary. Its not specific to this integration, but there are very few reports of this happening for anything other than this integration. Perhaps a specific library that isnt frequently used has a bug?

**Comment by tomaae** [comment]
You will get the same issue even if you  install HA from scratch directly on x64 debian. it will crash on first run, unable to install its own UI package.
Only common thing here is actually using mikrotik as a router with DNS.

**Comment by Extrapilot1** [comment]
It pretty much has to be an IPV6 block somewhere. Id wager that many of us are running Adguard or PiHole. If IPV6 queries are blocked/disallowed, the update fails. I just removed the checkmark (the default) in Adguard for 'disable resolving of IPv6 addresses', and the Mikrotik integration reinstall worked- where before, it would fail unless I had HA's DNS pointing to an external DNS (i.e. 1.1.1.1). I dont know if there is a flag in the install builder for IPV6, but given than I havent seen anything like this sort of install failure with any other integration. It may be that there is a problem with how the updater is configured for some specific libraries.

**Comment by tomaae** [comment]
Nothing I can do about this error from integration side.
HA correctly lists requirements and passes them to pip(I think). Error happens after that.
Its certainly some weird circumstances, but it is not related to this integration.

**Comment by Extrapilot1** [comment]
The HA crew are going to point fingers at us or our configs, when everything works fine except for this integration as regards this error. I pinged via HA/SSH session the 'bad' DNS address as presented in the error log, and I got a clean DNS resolution (IPV4). And, I was able to download the file there, and via my web browser. So, it seems like it has to be something about the installer, or some lower-level component the installer uses, or some flag in the python library, that is involved. I dont know enough about how that stuff works to provide much help; Im a firmware guy mostly.

**Comment by tomaae** [comment]
It is not possible to be on integration side.
Prerequisite libraries are just defined in manifest, which HA uses to install whats needed. Integration is not even loaded at that time.
Reason you dont see it often is because library update is usually not necessary on integration updates.
Also, it does not affect only this integration. As I said before, you wont be able to even install fresh HA on linux, I was fighting with this only few weeks ago.

**Comment by pomah86** [comment]
Just updated to 2025.6 and received the same error, seems like I have to change DNS and so on again to make it work.

I guess something changed in 2025.5, I did not have issues with this before that release?
